services:
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:25.3
    restart: always
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - data:/var/lib/clickhouse
    environment:
      #CLICKHOUSE_DB: db_name
      #CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_USER: user
      CLICKHOUSE_PASSWORD: password
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  data:
