version: '3'

services:
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:22
    restart: always
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  data:
