services:
  rabbit:
    container_name: rabbitmq
    image: rabbitmq:4-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - data:/var/lib/rabbitmq

volumes:
  data:
