version: '3'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.5.3
    ports:
      - 9200:9200
    volumes:
      - data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  data:
