vaavaversion: '3'

services:
  vault:
    container_name: vault
    image: vault:1.13.3
    restart: always
    ports:
      - 8200:8200
    volumes:
      - data:/vault/data
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_DEV_ROOT_TOKEN_ID=00000000-0000-0000-0000-000000000000
    cap_add:
      - IPC_LOCK

volumes:
  data:
