version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
      - ./shared:/mnt/shared
    environment:
      MYSQL_ROOT_PASSWORD: 12345

volumes:
  data:
